export const GET_TASK_TYPE_SAGA = "GET_TASK_TYPE_SAGA";
export const GET_TASK_TYPE = "GET_TASK_TYPE";

export const GET_TASK_DETAIL_SAGA = "GET_TASK_DETAIL_SAGA";
export const GET_TASK_DETAIL = "GET_TASK_DETAIL";

export const UPDATE_STATUS_TASK_SAGA = "UPDATE_STATUS_TASK_SAGA";

export const CHANGE_TASK_DETAIL =   "CHANGE_TASK_DETAIL";

export const DELETE_ASSIGNEE_FROM_TASK = "DELETE_ASSIGNEE_FROM_TASK";

export const HANDLE_CHANGE_POST_API_SAGA = "HANDLE_CHANGE_POST_API_SAGA";