export const GET_USER_BY_PROJECT_ID_SAGA = "GET_USER_BY_PROJECT_ID_SAGA";
export const GET_USER_BY_PROJECT_ID = "GET_USER_BY_PROJECT_ID";

export const REGISTER_CYBERBUGS_SAGA = "REGISTER_CYBERBUGS_SAGA";
export const GET_ALL_USER_SAGA = "GET_ALL_USER_SAGA";
export const GET_ALL_USER = "Users/getUser";

export const CLICK_ON_USER_EDIT = "CLICK_ON_USER_EDIT";

export const UPDATE_USER_SAGA = "UPDATE_USER_SAGA";
export const UPDATE_USER = "UPDATE_USER";

export const DELETE_USER_SAGA = "DELETE_USER_SAGA";

export const SEARCH_USER_SAGA = "SEARCH_USER_SAGA";
export const SEARCH_USER = "SEARCH_USER";